### ISSUE TITLE
Error when fetching from Ledger nano s

### ISSUE THREAD

**Issue by aaronzomback** [btcpayserver/BTCPayServer.Vault#27] opened 2020-12-22 20:01 UTC
I receive this error when I try to generate BTC derivation scheme to configure my store with my hardware ledger wallet....

"An unexpected error happened. (Error reading JArray from JsonReader. Path '', line 0, position 0.)"

- running macOS High Sierra 10.13.6
- Ledger firmware: Secure Element 1.6.1 / Microcontroller 1.12 / Bootloader 0.11
- Bitcoin version: 1.5.1
-Tried both Firefox & Chrome
- Ledger Live app is closed
-Tried BTC Pay Vault version 1.0.7 and 1.0.6

**Comment by NicolasDorier** [comment] 2020-12-23 13:10
You are the second one reporting this.
I never could reproduce. I think @britttttk  tried on mac and could not as well.
Are you good enough in dotnet to debug the situation?

**Comment by NicolasDorier** [comment] 2020-12-23 13:11
Do you see better logs in btcpayserver itself? Can you run the vault in command line to maybe see more logs?

**Comment by aaronzomback** [comment] 2020-12-23 13:32
Hey @NicolasDorier thanks for the response. I decided to put this aside and connect with my electrum wallet instead, which is working. Open source FTW!

**Comment by NicolasDorier** [comment] 2020-12-23 13:40
@aaronzomback just be aware about gap limit issues (see our doc) when you do this.
Also with electrum you leak your addresses to third party. I wished you could help us to debug your issue  instead :(

**Comment by aaronzomback** [comment] 2020-12-23 13:55
@NicolasDorier didn't know that about the 3rd party leak, you mean the public keys, or IP address? I'm still interested in connecting my Ledger instead. Although I am not familiar with running dotnet. I am with command line - are there docs to run vault in command line? Maybe I can update you better with the errors then.

**Comment by NicolasDorier** [comment] 2020-12-23 14:51
yeah you can git clone this repo and run `dotnet run` from the `BTCPayServer.Vault` folder.
You need to install dotnet sdk 3.1.404 on https://dotnet.microsoft.com/download/visual-studio-sdks

You leak both, public keys and IP to the server electrum connects to.

**Comment by pavlenex** [comment] 2020-12-25 11:58
Can't replicate. Most people reporting these issues either have outdated version of fw or don't know they need to confirm export public key on the device and wait too long.

**Comment by NicolasDorier** [comment] 2020-12-26 02:53
would be nice to at least understand where it comes from so can get better error message

**Comment by NicolasDorier** [comment] 2020-12-31 04:02
@britttttk I remember you could not reproduce on mac, but were you running latest of both Vault and Ledger firmware/app?

**Comment by britttttk** [comment] 2020-12-31 05:19
@NicolasDorier I tried to reproduce it with:
Vault: v1.0.7
BTCPay: v1.0.6.4
Ledger Nano S: firmware v1.5.5, Bitcoin v1.3.13
MacOS: Catalina 10.15.7

I'll update my ledger firmware to try it.. but @aaronzomback what version of BTCPay is this happening for you?

**Comment by aaronzomback** [comment] 2021-01-07 13:18
@britttttk I'm running 

BTCPay v1.0.6.4
Vault: v1.0.7
Ledger Nano S: firmware v1.6.1 (most recent as of 1/7/21), and Bitcoin v1.5.4
MacOS: HighSierra 10.13.6

**Comment by NicolasDorier** [comment] 2021-01-09 10:58
ping @britttttk  could repo/debug?

**Comment by NicolasDorier** [comment] 2021-02-02 01:29
Ping @aaronzomback are you tech savy enough to build the project in Debug and run it. It seems @britttttk does not manage to repro.

You just need .NET SDK 3.1, then run `dotnet run` in the `BTCPayServer.Vault` folder. You should then see debug logs that should help us.

**Comment by britttttk** [comment] 2021-02-02 10:00
@aaronzomback I updated everything to the latest. Can you try to run Vault from your terminal. If it's in your Applications: please try `/Applications/BTCPayServer\ Vault.app/Contents/MacOS/BTCPayServer.Vault` it will output some debug logs.

>generate BTC derivation scheme to configure my store

Does it happen for every kind of wallet you try to generate? Do you make it to this screen or it fails before?
![Screen Shot 2021-02-02 at 2 59 16 AM](https://user-images.githubusercontent.com/39231115/106583758-af47f280-6502-11eb-8d8a-eccad1dfec84.png)

**Comment by pavlenex** [comment] 2021-02-02 10:20
@britttttk would be good to write up how to find debug logs in the [issue template ](https://github.com/btcpayserver/BTCPayServer.Vault/blob/master/.github/ISSUE_TEMPLATE/----bug-report-.md)

**Comment by aaronzomback** [comment] 2021-02-02 12:01
@NicolasDorier I'm studying to become computer scientist/developer so I'm learning new things every day and will be glad to help the community with this. 

When I run vault from my terminal, should I have my ledger connect via usb to my computer?

I was actually able to configure xpub and connect to my BlueWallet just fine.

**Comment by NicolasDorier** [comment] 2021-02-02 13:02
@britttttk @aaronzomback you need to download .NET Core 3.1, clone this repo, then run `dotnet run` from inside the `BTCPayServer.Vault` directory.

Without this, you don't have debug logs.

Just run Vault like this, plug ledger, then try again to add your xpub via btcpay.

**Comment by aaronzomback** [comment] 2021-02-02 13:53
@NicolasDorier followed all your instructions and cloned this repo, but I'm getting this error in the CLI

`Couldn't find a project to run. Ensure a project exists in /Users/aaronzomback/Sites/BTCPAY/BTCPayServer.Vault, or pass the path to the project using --project.`

**Comment by NicolasDorier** [comment] 2021-02-02 13:55
@aaronzomback go in the BTCPayServer.Vault in the repo so `BTCPayServer.Vault/BTCPayServer.Vault`

**Comment by aaronzomback** [comment] 2021-02-02 14:01
@NicolasDorier is there a specific project I should run within that final cd?

I'm getting this message when entering `dotnet run`

`Specify which project file to use because /Users/aaronzomback/Sites/BTCPAY/BTCPayServer.Vault/BTCPayServer.Vault contains more than one project file.`

The first time I entered I receveived the above message followed by 
`Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Cli.Utils.ProcessReaper.HandleProcessExit(Object sender, EventArgs args)
   at System.AppContext.OnProcessExit()
[1]    1745 abort      dotnet run`

**Comment by NicolasDorier** [comment] 2021-02-02 14:56
@aaronzomback  `dotnet run BTCPayServer.Vault.csproj`

**Comment by aaronzomback** [comment] 2021-02-02 15:17
I tried running that in the dir but still gives me
`Specify which project file to use because /Users/aaronzomback/Sites/BTCPAY/BTCPayServer.Vault/BTCPayServer.Vault contains more than one project file.`

**Comment by NicolasDorier** [comment] 2021-02-03 06:59
`dotnet run -p BTCPayServer.Vault.csproj`

**Comment by NicolasDorier** [comment] 2021-02-05 01:07
@aaronzomback we found somebody else having the same issue.

It would be helpful if you can help us on finding the issue.

**Comment by aaronzomback** [comment] 2021-02-05 12:20
@NicolasDorier 

Running `dotnet run -p BTCPayServer.Vault.csproj` in the BTCPayServer repo doesn't seem to be producing anything in my CLI when the vault tries to fetch my ledger device.

If my BTCPayServer is not started the command prompts this...
`dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
      Hosting starting
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using '/Users/aaronzomback/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
info: BTCPayServer.Vault.Hwi[0]
      Ensuring hwi program is deployed...`

Otherwise, if my BTCPayServer is running, I receive the usual error when ledger connected in my BTCPayServer vault 
` An unexpected error happened. (Error reading JArray from JsonReader. Path '', line 0, position 0.)`
And then in my CLI it exits the dotnet command and prompts a blank new line

**Comment by NicolasDorier** [comment] 2021-02-06 06:05
@aaronzomback the CLI is crashing? it shows no error?

**Comment by aaronzomback** [comment] 2021-02-10 14:01
@NicolasDorier not sure if it's necessarily crashing, but it's true that it shows no error. Are you sure dotnet is the correct debugger?

**Comment by NicolasDorier** [comment] 2021-02-10 14:19
@aaronzomback if you run with `dotnet run` you normally see which are the exact parameters I send to hwi and the response.

**Comment by yeru83** [comment] 2021-07-02 08:21
So quiet... hey, I hope everyone is doing well... any progress on the issue?

**Comment by NicolasDorier** [comment] 2021-07-09 07:04
I replied to you on https://github.com/btcpayserver/BTCPayServer.Vault/issues/29

**Comment by NicolasDorier** [comment] 2021-07-09 07:04
Closing this one as we got no feedback

**Closed by NicolasDorier** 2021-07-09 07:04 UTC
