### ISSUE TITLE
Vault 2.0.3 does not start in Windows 11

### ISSUE THREAD

**Issue by zeddy1** [btcpayserver/BTCPayServer.Vault#48] opened 2022-07-04 10:13 UTC
**Describe the bug**

**Your  BTCPay Environment (please complete the following information):**

- BTCPay Server Version:    1.5.4.0 
- BTCPay Server Vault app version:  2.0.3  
- Deployment Method:  Docker      

**Your local environment (please complete the following information):**

- Your operating system Windows 11 
- Browser: Chrome                 

**Your hardware wallet details  (please complete the following information):**

- Hardware wallet name: Ledger X
- Hardware wallet version:
- Hardware wallet firmware, bootloader, microcontroller verisons (where applicable):

**Additional context**

v2.0.3 installs fine, but fails to start in Windows 11. No pop-up box or error message.

Uninstalled, installed v2.0.2, which works as intended.

**Comment by NicolasDorier** [comment] 2022-07-15 06:03
you are right, will check

**Comment by NicolasDorier** [comment] 2022-07-15 07:09
Fixed in 2.0.4, it was caused by binary trimming that is a bit aggressive in .net6.0. The binaries are a bit bigger now. Will try to put it back later.

**Closed by NicolasDorier** 2022-07-15 07:09 UTC
